project_id: '470762'
api_token_env: CROWDIN_PERSONAL_TOKEN
commit_message: 'Crowdin: new translations for %original_file_name% (%language%)'
append_commit_message: false
files:
  - source: /languages/en-US/*.json
    translation: /languages/%locale%/%original_file_name%
